# Generated by Django 6.0.3 on 2026-06-27 18:54

import uuid
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllowRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("ua", "User-agent"),
                            ("ip", "IP address"),
                            ("cidr", "CIDR range"),
                            ("composite", "Composite"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="rule type",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("regex", "Regex"),
                            ("contains", "Contains"),
                            ("cidr", "CIDR"),
                        ],
                        max_length=20,
                        verbose_name="match type",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Value to match against (IP, CIDR, user-agent string, or regex).",
                        max_length=2048,
                        verbose_name="pattern",
                    ),
                ),
                (
                    "verify_rdns",
                    models.BooleanField(
                        default=False,
                        help_text="Require reverse-DNS lookup to confirm the IP belongs to a trusted network.",
                        verbose_name="verify rDNS",
                    ),
                ),
                (
                    "rdns_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Regex or suffix matched against the PTR record when verify_rdns is enabled.",
                        max_length=255,
                        verbose_name="rDNS pattern",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="active"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "allow rule",
                "verbose_name_plural": "allow rules",
                "db_table": "django_waf_allow_rule",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "is_active"],
                        name="django_waf_ar_type_active_idx",
                    ),
                    models.Index(fields=["is_active"], name="django_waf_ar_active_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BlockRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("ua", "User-agent"),
                            ("ip", "IP address"),
                            ("cidr", "CIDR range"),
                            ("composite", "Composite"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="rule type",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("regex", "Regex"),
                            ("contains", "Contains"),
                            ("cidr", "CIDR"),
                        ],
                        max_length=20,
                        verbose_name="match type",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        db_index=True,
                        help_text="Value to match against (IP, CIDR, user-agent string, or regex).",
                        max_length=2048,
                        verbose_name="pattern",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("block", "Block"),
                            ("challenge", "Challenge"),
                            ("throttle", "Throttle"),
                            ("log_only", "Log only"),
                        ],
                        default="block",
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=100,
                        help_text="Lower numbers are evaluated first.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="active"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("auto", "Auto-generated"),
                            ("feed", "Threat feed"),
                        ],
                        default="admin",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Leave blank for rules that never expire.",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(default=0, verbose_name="hit count"),
                ),
                (
                    "last_hit_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last hit at"),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Confidence score from 0.00 to 1.00 (feed-sourced rules only).",
                        max_digits=3,
                        verbose_name="confidence",
                    ),
                ),
                (
                    "feed_first_seen",
                    models.DateField(blank=True, null=True, verbose_name="feed first seen"),
                ),
                (
                    "feed_reporters",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of sites that reported this threat to the collective feed.",
                        verbose_name="feed reporters",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "block rule",
                "verbose_name_plural": "block rules",
                "db_table": "django_waf_block_rule",
                "ordering": ["priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "is_active"],
                        name="django_waf_br_type_active_idx",
                    ),
                    models.Index(
                        fields=["source", "is_active"],
                        name="django_waf_br_src_active_idx",
                    ),
                    models.Index(
                        fields=["priority", "is_active"],
                        name="django_waf_br_prio_active_idx",
                    ),
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["expires_at"],
                        name="django_waf_br_exp_active_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChallengeToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(db_index=True, max_length=128, unique=True, verbose_name="token"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, verbose_name="IP address"),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Number of leading zero bits required in the solution hash.",
                        verbose_name="difficulty",
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        blank=True,
                        help_text="The nonce submitted by the client when solving the challenge.",
                        max_length=128,
                        verbose_name="nonce",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("solved", "Solved"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="issued at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                (
                    "solved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="solved at"),
                ),
            ],
            options={
                "verbose_name": "challenge token",
                "verbose_name_plural": "challenge tokens",
                "db_table": "django_waf_challenge_token",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "status"],
                        name="django_waf_ct_ip_status_idx",
                    ),
                    models.Index(fields=["expires_at"], name="django_waf_ct_expires_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IPReputation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True, verbose_name="IP address"),
                ),
                (
                    "total_requests",
                    models.PositiveIntegerField(default=0, verbose_name="total requests"),
                ),
                (
                    "blocked_requests",
                    models.PositiveIntegerField(default=0, verbose_name="blocked requests"),
                ),
                (
                    "challenged_requests",
                    models.PositiveIntegerField(default=0, verbose_name="challenged requests"),
                ),
                (
                    "challenge_passes",
                    models.PositiveIntegerField(default=0, verbose_name="challenge passes"),
                ),
                (
                    "challenge_failures",
                    models.PositiveIntegerField(default=0, verbose_name="challenge failures"),
                ),
                (
                    "distinct_ua_count",
                    models.PositiveIntegerField(default=0, verbose_name="distinct UA count"),
                ),
                (
                    "threat_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Normalised threat score from 0.00 (clean) to 1.00 (high threat).",
                        max_digits=3,
                        verbose_name="threat score",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="last seen at",
                    ),
                ),
                (
                    "window_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the current scoring window.",
                        null=True,
                        verbose_name="window start",
                    ),
                ),
                (
                    "window_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the current scoring window.",
                        null=True,
                        verbose_name="window end",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP reputation",
                "verbose_name_plural": "IP reputations",
                "db_table": "django_waf_ip_reputation",
                "ordering": ["-threat_score"],
                "indexes": [
                    models.Index(fields=["threat_score"], name="django_waf_ipr_score_idx"),
                    models.Index(fields=["last_seen_at"], name="django_waf_ipr_last_seen_idx"),
                    models.Index(fields=["distinct_ua_count"], name="django_waf_ipr_ua_count_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, verbose_name="IP address"),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=1024, verbose_name="user-agent"),
                ),
                ("path", models.CharField(max_length=2048, verbose_name="path")),
                (
                    "method",
                    models.CharField(default="GET", max_length=16, verbose_name="method"),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("blocked", "Blocked"),
                            ("challenged", "Challenged"),
                            ("throttled", "Throttled"),
                            ("passed", "Passed"),
                            ("logged", "Logged"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="verdict",
                    ),
                ),
                (
                    "matched_rule_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="matched rule ID",
                    ),
                ),
                (
                    "matched_rule_type",
                    models.CharField(
                        blank=True,
                        choices=[("block", "Block rule"), ("allow", "Allow rule")],
                        default="",
                        help_text="Which rule table matched — 'block' = a BlockRule, 'allow' = an AllowRule. This is the source table, NOT the enforced action: a BlockRule with action=challenge produces matched_rule_type='block' and verdict='challenged'. Use the verdict column for enforcement reporting; use this column for rule-source auditing.",
                        max_length=10,
                        verbose_name="matched rule type",
                    ),
                ),
                (
                    "anomaly_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="anomaly score",
                    ),
                ),
                (
                    "response_code",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="response code"),
                ),
                (
                    "referer",
                    models.CharField(
                        blank=True,
                        help_text="HTTP Referer header value, useful for identifying bot traffic sources.",
                        max_length=2048,
                        verbose_name="referer",
                    ),
                ),
                (
                    "http_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash of normalised HTTP headers — identifies real client software.",
                        max_length=64,
                        verbose_name="HTTP fingerprint",
                    ),
                ),
                (
                    "fingerprint_verdict",
                    models.CharField(
                        blank=True,
                        help_text="Fingerprint classification: browser, bot, suspicious, unknown.",
                        max_length=20,
                        verbose_name="fingerprint verdict",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=2, verbose_name="country code"),
                ),
            ],
            options={
                "verbose_name": "request log",
                "verbose_name_plural": "request logs",
                "db_table": "django_waf_request_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "verdict"],
                        name="django_waf_rl_ts_verdict_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="django_waf_rl_ip_ts_idx",
                    ),
                    models.Index(
                        fields=["verdict", "timestamp"],
                        name="django_waf_rl_verdict_ts_idx",
                    ),
                    models.Index(fields=["matched_rule_id"], name="django_waf_rl_rule_id_idx"),
                ],
            },
        ),
    ]
