# Generated by Django 6.0.3 on 2026-07-18 12:11

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_waf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowrule",
            name="confidence",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Confidence score from 0.00 to 1.00 (feed-sourced rules only).",
                max_digits=3,
                verbose_name="confidence",
            ),
        ),
        migrations.AddField(
            model_name="allowrule",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Leave blank for rules that never expire.",
                null=True,
                verbose_name="expires at",
            ),
        ),
        migrations.AddField(
            model_name="allowrule",
            name="feed_first_seen",
            field=models.DateField(blank=True, null=True, verbose_name="feed first seen"),
        ),
        migrations.AddField(
            model_name="allowrule",
            name="feed_reporters",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of sites that reported this allowlist entry to the collective feed.",
                verbose_name="feed reporters",
            ),
        ),
        migrations.AddField(
            model_name="allowrule",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("auto", "Auto-generated"),
                    ("feed", "Threat feed"),
                ],
                default="admin",
                max_length=20,
                verbose_name="source",
            ),
        ),
        migrations.AddIndex(
            model_name="allowrule",
            index=models.Index(fields=["source", "is_active"], name="django_waf_ar_src_active_idx"),
        ),
    ]
