# Generated by Django 6.0.3 on 2026-08-01

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("django_waf", "0003_seed_verified_crawlers"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("middleware", "Middleware"),
                    ("nginx_log", "Nginx access log"),
                ],
                db_index=True,
                default="middleware",
                help_text=(
                    "Which pipeline wrote this row. 'middleware' rows carry a real WAF "
                    "verdict; 'nginx_log' rows have a verdict inferred from the access "
                    "log status code (#32). The default is 'middleware' so existing "
                    "and future middleware writes are correctly tagged without the "
                    "middleware needing to pass source explicitly."
                ),
                max_length=20,
                verbose_name="source",
            ),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="source_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Deterministic identity for a source event, used to dedupe "
                    "re-ingested nginx access-log lines (#32). Populated only for "
                    "source='nginx_log' rows; middleware rows leave this blank."
                ),
                max_length=128,
                verbose_name="source event ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestlog",
            constraint=models.UniqueConstraint(
                condition=Q(("source", "nginx_log")) & ~Q(("source_event_id", "")),
                fields=("source", "source_event_id"),
                name="django_waf_rl_nginx_event_uniq",
            ),
        ),
    ]
