# Generated by Django 6.0.3 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_waf", "0004_requestlog_source_and_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockrule",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not applicable"),
                    ("pending", "Pending review"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("expired_unreviewed", "Expired unreviewed"),
                ],
                db_index=True,
                default="not_applicable",
                help_text="Review state for an auto-generated rule (BR-ANOM-010). Stays 'not applicable' for admin and feed rules, and for auto rules that were never queued for review.",
                max_length=20,
                verbose_name="review status",
            ),
        ),
        migrations.AddField(
            model_name="blockrule",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when review_status transitions to confirmed or rejected.",
                null=True,
                verbose_name="reviewed at",
            ),
        ),
        migrations.AlterField(
            model_name="blockrule",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Populated for feed-sourced rules today. Auto-generated rules populate this with a human-readable rendering of the detection evidence (BR-ANOM-009).",
                verbose_name="notes",
            ),
        ),
        migrations.AddIndex(
            model_name="blockrule",
            index=models.Index(fields=["source", "review_status"], name="django_waf_br_review_idx"),
        ),
    ]
