# Generated by Django 5.2.17 on 2026-09-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_waf", "0006_blockrule_detectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="http_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of normalised HTTP headers: identifies real client software.",
                max_length=64,
                verbose_name="HTTP fingerprint",
            ),
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="matched_rule_type",
            field=models.CharField(
                blank=True,
                choices=[("block", "Block rule"), ("allow", "Allow rule")],
                default="",
                help_text="Which rule table matched: 'block' = a BlockRule, 'allow' = an AllowRule. This is the source table, NOT the enforced action: a BlockRule with action=challenge produces matched_rule_type='block' and verdict='challenged'. Use the verdict column for enforcement reporting; use this column for rule-source auditing.",
                max_length=10,
                verbose_name="matched rule type",
            ),
        ),
    ]
