# Generated by Django 6.0.3 on 2026-04-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_waf", "0002_alter_allowrule_created_at_alter_allowrule_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="referer",
            field=models.CharField(
                blank=True,
                help_text="HTTP Referer header value, useful for identifying bot traffic sources.",
                max_length=2048,
                verbose_name="referer",
            ),
        ),
    ]
