# Generated by Django 6.0.3 on 2026-04-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_waf", "0003_requestlog_referer"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="fingerprint_verdict",
            field=models.CharField(
                blank=True,
                help_text="Fingerprint classification: browser, bot, suspicious, unknown.",
                max_length=20,
                verbose_name="fingerprint verdict",
            ),
        ),
        migrations.AddField(
            model_name="requestlog",
            name="http_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of normalised HTTP headers — identifies real client software.",
                max_length=64,
                verbose_name="HTTP fingerprint",
            ),
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="matched_rule_type",
            field=models.CharField(
                blank=True,
                choices=[("block", "Block rule"), ("allow", "Allow rule")],
                default="",
                max_length=10,
                verbose_name="matched rule type",
            ),
        ),
    ]
