# Generated by Django 6.0.3 on 2026-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_waf", "0004_requestlog_fingerprint_verdict_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="matched_rule_type",
            field=models.CharField(
                blank=True,
                choices=[("block", "Block rule"), ("allow", "Allow rule")],
                default="",
                help_text="Which rule table matched — 'block' = a BlockRule, 'allow' = an AllowRule. This is the source table, NOT the enforced action: a BlockRule with action=challenge produces matched_rule_type='block' and verdict='challenged'. Use the verdict column for enforcement reporting; use this column for rule-source auditing.",
                max_length=10,
                verbose_name="matched rule type",
            ),
        ),
    ]
