# Generated by Django 6.0.3 on 2026-05-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_waf", "0005_alter_requestlog_matched_rule_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="method",
            field=models.CharField(default="GET", max_length=16, verbose_name="method"),
        ),
    ]
