"""
Blocklist generator service for icv-waf.

Reads active BlockRules and writes a valid nginx map/geo configuration file.
Writes are atomic via a temp-file-then-rename (BR-BL-002).
"""

from __future__ import annotations

import contextlib
import logging
import os
import signal
import subprocess
import tempfile

logger = logging.getLogger("icv_waf.blocklist_generator")


def generate_nginx_blocklist(output_path: str | None = None) -> int:
    """Generate the nginx blocklist configuration file from active BlockRules.

    Queries BlockRule.objects.for_nginx() (rule_type in ('ip', 'cidr', 'ua')
    with action in ('block', 'throttle') — BR-BL-001, BR-BL-005) then writes:

    - ``map $http_user_agent $waf_block_ua { ... }`` for UA rules
    - ``geo $waf_block_ip { ... }`` for IP/CIDR rules

    The file is written atomically (BR-BL-002).

    Args:
        output_path: Override output path. Defaults to ICV_WAF_NGINX_BLOCKLIST_PATH.

    Returns:
        Integer count of rules written.
    """
    from icv_waf import conf
    from icv_waf.models import BlockRule

    dest = output_path or conf.ICV_WAF_NGINX_BLOCKLIST_PATH

    rules = list(BlockRule.objects.for_nginx())
    rule_count = len(rules)

    ua_rules = [r for r in rules if r.rule_type == "ua"]
    ip_rules = [r for r in rules if r.rule_type in ("ip", "cidr")]

    lines: list[str] = [
        "# Generated by icv-waf — do not edit manually\n",
        "# This file is regenerated every 5 minutes by the generate_blocklist task.\n\n",
    ]

    # UA map block
    lines.append("map $http_user_agent $waf_block_ua {\n")
    lines.append("    default 0;\n")
    for rule in ua_rules:
        escaped = _nginx_escape_ua(rule.pattern, rule.match_type)
        if escaped:
            lines.append(f"    {escaped} 1;\n")
    lines.append("}\n\n")

    # IP geo block
    lines.append("geo $waf_block_ip {\n")
    lines.append("    default 0;\n")
    for rule in ip_rules:
        # For IP rules the pattern is already a valid IP or CIDR
        safe = rule.pattern.strip()
        if safe:
            lines.append(f"    {safe} 1;\n")
    lines.append("}\n")

    conf_dir = os.path.dirname(dest)
    if conf_dir:
        os.makedirs(conf_dir, exist_ok=True)

    # Atomic write: temp file in same directory, then rename (BR-BL-002)
    tmp_fd, tmp_path = tempfile.mkstemp(dir=conf_dir or ".", suffix=".conf.tmp")
    try:
        with os.fdopen(tmp_fd, "w") as fh:
            fh.writelines(lines)
        os.rename(tmp_path, dest)
    except Exception:
        with contextlib.suppress(OSError):
            os.unlink(tmp_path)
        raise

    logger.info("icv-waf: wrote %d rules to %s", rule_count, dest)
    return rule_count


def reload_nginx() -> bool:
    """Signal nginx to reload its configuration.

    Strategy (in order):
    1. **SIGHUP via PID file** (preferred) — reads the nginx master PID from
       ``ICV_WAF_NGINX_PID_PATH`` and sends SIGHUP directly. No subprocess,
       no sudo, no PATH required. Just needs read access to the PID file.
    2. **Subprocess command** (fallback) — runs ``ICV_WAF_NGINX_RELOAD_COMMAND``
       if the PID file is unavailable or unreadable.

    Errors are logged but do not raise — a failed reload leaves the previous
    config active (BR-BL-003).

    Returns:
        True if reload succeeded, False otherwise.
    """
    from icv_waf import conf

    # Strategy 1: SIGHUP via PID file
    if conf.ICV_WAF_NGINX_PID_PATH:
        result = _reload_via_pid(conf.ICV_WAF_NGINX_PID_PATH)
        if result is not None:
            return result
        # PID file unreadable — fall through to command

    # Strategy 2: subprocess command
    return _reload_via_command(conf.ICV_WAF_NGINX_RELOAD_COMMAND)


def _reload_via_pid(pid_path: str) -> bool | None:
    """Send SIGHUP to the nginx master process via its PID file.

    Returns:
        True if SIGHUP sent successfully, False if the process doesn't exist,
        None if the PID file is unreadable (caller should fall back).
    """
    try:
        with open(pid_path) as fh:
            pid = int(fh.read().strip())
    except (FileNotFoundError, ValueError, OSError):
        logger.debug("icv-waf: PID file %s unreadable — falling back to command", pid_path)
        return None

    try:
        os.kill(pid, signal.SIGHUP)
        logger.info("icv-waf: sent SIGHUP to nginx master (PID %d)", pid)
        return True
    except ProcessLookupError:
        logger.error("icv-waf: nginx PID %d not found — stale PID file?", pid)
        return False
    except PermissionError:
        logger.warning("icv-waf: no permission to signal PID %d — falling back to command", pid)
        return None
    except OSError as exc:
        logger.error("icv-waf: error sending SIGHUP to PID %d: %s", pid, exc)
        return False


def _reload_via_command(command: list[str]) -> bool:
    """Reload nginx via a subprocess command."""
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            logger.info("icv-waf: nginx reloaded via command")
            return True
        logger.error(
            "icv-waf: nginx reload command failed (exit %d): %s",
            result.returncode,
            result.stderr.strip(),
        )
        return False
    except FileNotFoundError:
        logger.error("icv-waf: nginx command not found in PATH — reload skipped")
        return False
    except subprocess.TimeoutExpired:
        logger.error("icv-waf: nginx reload command timed out after 10s")
        return False
    except OSError as exc:
        logger.error("icv-waf: nginx reload command error: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _nginx_escape_ua(pattern: str, match_type: str) -> str:
    """Format a UA pattern for inclusion in an nginx map block.

    Returns the nginx-formatted pattern string, or empty string if the pattern
    cannot be safely expressed.
    """
    pattern = pattern.strip()
    if not pattern:
        return ""

    if match_type == "exact":
        # Exact match — quote the string
        escaped = pattern.replace('"', '\\"')
        return f'"{escaped}"'

    if match_type in ("regex", "contains"):
        # nginx map uses ~* for case-insensitive regex prefix
        if match_type == "contains":
            # Wrap as a case-insensitive regex
            import re

            escaped = re.escape(pattern)
            return f'"~*{escaped}"'
        # regex — use as-is with ~* prefix
        return f'"~*{pattern}"'

    return ""
