"""
Blocklist generator service for icv-waf.

Reads active BlockRules and writes a valid nginx map/geo configuration file.
Writes are atomic via a temp-file-then-rename (BR-BL-002).
"""

from __future__ import annotations

import contextlib
import logging
import os
import subprocess
import tempfile

logger = logging.getLogger("icv_waf.blocklist_generator")


def generate_nginx_blocklist(output_path: str | None = None) -> int:
    """Generate the nginx blocklist configuration file from active BlockRules.

    Queries BlockRule.objects.for_nginx() (rule_type in ('ip', 'cidr', 'ua')
    with action in ('block', 'throttle') — BR-BL-001, BR-BL-005) then writes:

    - ``map $http_user_agent $waf_block_ua { ... }`` for UA rules
    - ``geo $waf_block_ip { ... }`` for IP/CIDR rules

    The file is written atomically (BR-BL-002).

    Args:
        output_path: Override output path. Defaults to ICV_WAF_NGINX_BLOCKLIST_PATH.

    Returns:
        Integer count of rules written.
    """
    from icv_waf import conf
    from icv_waf.models import BlockRule

    dest = output_path or conf.ICV_WAF_NGINX_BLOCKLIST_PATH

    rules = list(BlockRule.objects.for_nginx())
    rule_count = len(rules)

    ua_rules = [r for r in rules if r.rule_type == "ua"]
    ip_rules = [r for r in rules if r.rule_type in ("ip", "cidr")]

    lines: list[str] = [
        "# Generated by icv-waf — do not edit manually\n",
        "# This file is regenerated every 5 minutes by the generate_blocklist task.\n\n",
    ]

    # UA map block
    lines.append("map $http_user_agent $waf_block_ua {\n")
    lines.append("    default 0;\n")
    for rule in ua_rules:
        escaped = _nginx_escape_ua(rule.pattern, rule.match_type)
        if escaped:
            lines.append(f"    {escaped} 1;\n")
    lines.append("}\n\n")

    # IP geo block
    lines.append("geo $waf_block_ip {\n")
    lines.append("    default 0;\n")
    for rule in ip_rules:
        # For IP rules the pattern is already a valid IP or CIDR
        safe = rule.pattern.strip()
        if safe:
            lines.append(f"    {safe} 1;\n")
    lines.append("}\n")

    conf_dir = os.path.dirname(dest)
    if conf_dir:
        os.makedirs(conf_dir, exist_ok=True)

    # Atomic write: temp file in same directory, then rename (BR-BL-002)
    tmp_fd, tmp_path = tempfile.mkstemp(dir=conf_dir or ".", suffix=".conf.tmp")
    try:
        with os.fdopen(tmp_fd, "w") as fh:
            fh.writelines(lines)
        os.rename(tmp_path, dest)
    except Exception:
        with contextlib.suppress(OSError):
            os.unlink(tmp_path)
        raise

    logger.info("icv-waf: wrote %d rules to %s", rule_count, dest)
    return rule_count


def reload_nginx() -> bool:
    """Signal nginx to reload its configuration.

    Runs the command defined by ``ICV_WAF_NGINX_RELOAD_COMMAND`` (default:
    ``["nginx", "-s", "reload"]``) in a subprocess with a 10-second timeout.
    Errors are logged but do not raise — a failed reload leaves the previous
    config active (BR-BL-003).

    Returns:
        True if reload succeeded, False otherwise.
    """
    from icv_waf import conf

    try:
        result = subprocess.run(
            conf.ICV_WAF_NGINX_RELOAD_COMMAND,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            logger.info("icv-waf: nginx reloaded successfully")
            return True
        logger.error(
            "icv-waf: nginx reload failed (exit %d): %s",
            result.returncode,
            result.stderr.strip(),
        )
        return False
    except FileNotFoundError:
        logger.error("icv-waf: nginx not found in PATH — reload skipped")
        return False
    except subprocess.TimeoutExpired:
        logger.error("icv-waf: nginx reload timed out after 10s")
        return False
    except OSError as exc:
        logger.error("icv-waf: nginx reload error: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _nginx_escape_ua(pattern: str, match_type: str) -> str:
    """Format a UA pattern for inclusion in an nginx map block.

    Returns the nginx-formatted pattern string, or empty string if the pattern
    cannot be safely expressed.
    """
    pattern = pattern.strip()
    if not pattern:
        return ""

    if match_type == "exact":
        # Exact match — quote the string
        escaped = pattern.replace('"', '\\"')
        return f'"{escaped}"'

    if match_type in ("regex", "contains"):
        # nginx map uses ~* for case-insensitive regex prefix
        if match_type == "contains":
            # Wrap as a case-insensitive regex
            import re

            escaped = re.escape(pattern)
            return f'"~*{escaped}"'
        # regex — use as-is with ~* prefix
        return f'"~*{pattern}"'

    return ""
